service: uptime-monitoring

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-northeast-1'}
  profile: ${self:custom.config.aws_profile}
  memorySize: 128
  timeout: 8
  logRetentionInDays: 30
  iamRoleStatements:
    - Effect: Allow
      Resource:
        Fn::GetAtt: [DDBTable, Arn]
      Action:
        - dynamodb:*

custom:
  config: ${file(./config.yml)}

plugins:
  - serverless-webpack

functions:
  main:
    handler: handler.main
    environment:
      targetEndpoint: ${self:custom.config.target_endpoint}
      slackWebhookUrl: ${self:custom.config.slack_webhook_url}
    events:
      - schedule: rate(5 minutes)

resources:
  Resources:
    DDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: uptime-monitoring-state-${opt:stage, 'dev'}
        AttributeDefinitions:
          - AttributeName: key
            AttributeType: S
        KeySchema:
          - AttributeName: key
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
