service: uptime-monitoring

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-northeast-1'}
  profile: ${self:custom.config.aws_profile}
  memorySize: 128
  timeout: 8
  logRetentionInDays: 30

custom:
  config: ${file(./config.yml)}

plugins:
  - serverless-webpack

functions:
  main:
    handler: handler.main
    environment:
      targetEndpoint: ${self:custom.config.target_endpoint}
      slackWebhookUrl: ${self:custom.config.slack_webhook_url}
    events:
      - schedule: rate(5 minutes)
