name: Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: cache node_modules
      id: node_modules_cache_id
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          packages/*/node_modules
          distributions/*/node_modules
        key: node-v${{ matrix.node-version }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
    - name: yarn install, lint, build
      run: |
        cp config.test.yml config.yml
        yarn install
        yarn lint
        yarn build
      env:
        CI: true
